export const endpoint = ``;
export const prodEndpoint = ``;
export const endpoint_ws = ``;
export const prodEndpoint_ws = ``;
export const FB_APP_ID = ``;
export const GOOGLE_MAPS_API_KEY = "";
// export const PUSHER_API = ``;
export const PUSHER_API_PROD = ``;
export const PUSHER_API = ``;
